name: C Project Build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Build on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: gcc -o server server.c
    
    - name: Build on macOS
      if: matrix.os == 'macos-latest'
      run: clang -o server server.c
    
    - name: Build on Windows
      if: matrix.os == 'windows-latest'
      run: gcc -o server.exe server.c -lws2_32
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: server-${{ matrix.os }}
        path: |
          server${{ matrix.os == 'windows-latest' && '.exe' || '' }}
