name: Build and Release

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: server
            compile_cmd: gcc -o server server.c
            zip_cmd: zip -j
            release_name: web-server-Linux-x86_64
          - os: windows-latest
            artifact_name: server.exe
            compile_cmd: gcc -o server.exe server.c -lws2_32
            zip_cmd: powershell Compress-Archive
            release_name: web-server-Windows-AMD64
          - os: macos-latest
            artifact_name: server
            compile_cmd: clang -arch x86_64 -o server server.c
            zip_cmd: zip -j
            release_name: web-server-MacOS-x86_64
        
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Compile
      run: ${{ matrix.compile_cmd }}
    
    - name: Prepare Release
      run: |
        mkdir release
        ${{ matrix.zip_cmd }} release/${{ matrix.release_name }}_Release.zip ${{ matrix.artifact_name }}
    
    - name: Upload Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh release upload "${{ github.ref_name }}" release/${{ matrix.release_name }}_Release.zip
